version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "80:8080"
    volumes:
     - database:/usr/local/tomcat/webapps/bimserver/WEB-INF/database
     - plugins:/usr/local/tomcat/webapps/bimserver/WEB-INF/plugins
volumes:
  database: {}
  plugins: {}
