version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - web-inf:/usr/local/tomcat/webapps/bimserver/WEB-INF/
    environment:
      VIRTUAL_HOST: bim-server.tbe-team.com
      VIRTUAL_PORT: 8080
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
volumes:
  web-inf: {}
