version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "80:8080"
    volumes:
     - web-inf:/usr/local/tomcat/webapps/bimserver/WEB-INF/
volumes:
  web-inf: {}
